spring:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_service_db
    username: dev
    password: devpass

  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: serukalinin@gmail.com
    password: hlbu gorj pcgk vpgj
    protocol: smtp
    properties:
      mail.transport.protocol: smtp
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true


  redis:
    data:
      host: localhost
      port: 6379
      password: devpass

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    com.example.auth_service:
      service: DEBUG
      config: DEBUG
      controller: INFO
      repository: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

auth_service:
  issuer: auth_service
  jwtSecret: mySecretKey
  jwtLifeTimeDuration: 86400000